module.exports = {
    LOFT_PLAYLIST_ID: "PLgE8B1SdCTDshXW3ET6UHQQzav65px_Qx",
    WOODFOREST_PLAYLIST_ID: "PLgE8B1SdCTDvBQalk1CLJQ6tLjSxsXwfw",
    TRADITIONAL_PLAYLIST_ID: "PLgE8B1SdCTDtykVWGL75lJHPhfnY5CqEG",
    HARVEST_PLAYLIST_ID: "PLgE8B1SdCTDvc8Ogp6Lced5yCf7x9-JJB",
  };